server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nuclei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update